INSERT INTO jogadores (nome, idade, time_futebol) VALUES
('Lionel Messi', 36, 'Inter Miami'),
('Cristiano Ronaldo', 39, 'Al-Nassr'),
('Neymar Jr', 32, 'Al-Hilal'),
('Kylian Mbappé', 25, 'Paris Saint-Germain'),
('Karim Benzema', 36, 'Al-Ittihad'),
('Mohamed Salah', 31, 'Liverpool'),
('Kevin De Bruyne', 32, 'Manchester City'),
('Erling Haaland', 23, 'Manchester City'),
('Robert Lewandowski', 35, 'Barcelona'),
('Luka Modrić', 38, 'Real Madrid'),
('Thibaut Courtois', 31, 'Real Madrid'),
('Virgil van Dijk', 32, 'Liverpool'),
('Harry Kane', 30, 'Bayern Munich'),
('Toni Kroos', 34, 'Real Madrid'),
('Manuel Neuer', 38, 'Bayern Munich'),
('Sergio Agüero', 35, 'Retirado (ex-Manchester City)'),
('Luis Suárez', 37, 'Grêmio'),
('Gareth Bale', 34, 'Retirado (ex-Real Madrid)'),
('Iker Casillas', 42, 'Retirado (ex-Real Madrid)'),
('Xavi Hernández', 44, 'Retirado (ex-Barcelona)');